---
enable_zebra: 'yes'
enable_bgpd: 'no'
enable_ospfd: 'yes'
enable_ospf6d: 'no'
enable_ripd: 'no'
enable_ripngd: 'no'
enable_isisd: 'no'
enable_babeld: 'no'

password: "Quagga"

zebrad_conf:
  logfile: "/var/log/quagga/zebra.log"
  interfaces:
    - name: eth0
      options:
        - ip irdp multicast
        - link-detect
        - multicast
        - ipv6 nd suppress-ra
    - name: lo
      options:
        - ip irdp multicast
        - link-detect
        - multicast
  other:
    - "#autres lignes"

ospfd_conf:
  hostname: "OSPFv2"
  logfile: "/var/log/quagga/ospfd.log"
  interfaces:
    - eth0
    - lo
  redistribute:
    - connected
    - kernel
    - static
  other:
    - "#autres lignes"
